from .core import (
    sgn, k, reg, NOT, AND, OR, NAND, NOR, XOR, XNOR, AND_n, OR_n,
    eq, neq, gt, lt, ge, le, DEFAULT_XI, DEFAULT_KERNEL,
)
from .funcs import intf, par, maxf, minf, clamp, modf, delta_approx
from .applications import (
    kronecker_delta, levi_civita, dirac_delta_integral,
    line_intersection_y, collatz_step, collatz_sequence,
    choc_bar_source,
)
from .kernels import (
    KERNELS, apply_kernel, KERNEL_BOUNDARY_CONST,
    kernel_log_increment, kernel_fused_or_threshold, kernel_fused_or_is_true,
)
from .physics_bridge import (
    log_potential, log_charge, chemical_potential, occupation_from_charge,
    effective_temperature, log_potential_is_dilation_invariant,
)
from .partition import (
    empty_state_probability, or_n_from_empty_state, occupation_step_sech2,
    free_energy_log_domain, summary as partition_summary, why_no_phase_transition,
)
from .heat import xi_of_time, time_of_xi, heat_step_profile, heat_kernel_gaussian, gaussian_match
from .quantum_well import (
    box_heat_kernel, box_heat_kernel_eigen,
    infinite_well_propagator, infinite_well_propagator_eigen,
)
from .search import (
    soft_gt, soft_eq, soft_or, soft_and, anneal_solve, numeric_grad, l2_penalty,
    is_dont_care_variable, find_dont_care_variables,
)
from .field_theory import (
    kink_profile, kink_eom_residual, kink_energy_exact, topological_charge,
    kink_shape_mode_frequency, kink_continuum_threshold,
    kink_zero_mode_profile, kink_shape_mode_profile, kink_stability_spectrum_numeric,
    kink_antikink_collision, kink_antikink_velocity_scan,
)
from .stat_mech import box_partition_function, box_partition_function_exact, witten_index_toy
from .quantum_logic import (
    soft_povm, is_valid_povm, measurement_strength,
    soft_measurement_kraus, quantum_truth_value,
)
from .superconductivity import (
    bcs_gap_equation_residual, bcs_critical_temperature, bcs_gap,
    bcs_gap_zero_temperature, bcs_universal_ratio, BCS_UNIVERSAL_RATIO,
)
from .transport import (
    thermal_transport_window, transport_moment, lorenz_ratio,
    sommerfeld_heat_capacity_coefficient, electronic_heat_capacity,
    wiedemann_franz_check, LORENZ_NUMBER, kubo_dc_conductivity,
)
from .magnetism import (
    curie_weiss_magnetization, curie_weiss_susceptibility,
    curie_weiss_slope_at_zero, has_critical_point,
    pauli_susceptibility, landau_susceptibility, total_electron_susceptibility,
    MEAN_FIELD_BETA, MEAN_FIELD_GAMMA, MEAN_FIELD_AMPLITUDE, LANDAU_PAULI_RATIO,
)
from .optics import (
    ssh_transition_energies, dielectric_imaginary, spectral_weight, absorbance,
    cie_color_matching, spectrum_to_xyz, xyz_to_srgb, srgb_to_hex,
    transmitted_color, HC_EV_NM,
    eps2_from_hamiltonian, material_color_from_hamiltonian, color_saturation,
)
from .disorder import (
    disordered_chain, inverse_participation_ratio, localization_length,
    localization_exponent, one_dimension_has_no_mobility_edge,
    transfer_matrix_lambda, scaling_beta_function, anderson3d_critical_exponent,
    transfer_matrix_lambda_2d, beta_function_2d, dimensional_beta_survey,
    anderson3d_hamiltonian, ipr_times_n_3d,
    mean_level_spacing, smeared_dos_at_zero, resolution_exponent,
    resolution_exponent_auto, level_statistics_window_probe,
    required_xi_for_accuracy,
    PICKET_EXPONENT, GOE_EXPONENT, POISSON_EXPONENT,
    ANDERSON_WC, ANDERSON_LAMBDA_C, ANDERSON_NU,
)
from .criticality import (
    classify_bifurcation, bcs_linear_coefficient, bcs_beta_amplitude,
    curie_weiss_beta_amplitude, bifurcation_survey,
    PITCHFORK, PERIOD_DOUBLING, NO_BIFURCATION,
)
from .info_theory import (
    gaussian_variance, differential_entropy_gaussian,
    fisher_information_gaussian, de_bruijn_check,
    fisher_metric_gaussian, fisher_metric_matches_gauge_hyperbolic_metric,
    fisher_gaussian_curvature,
)
from .topology import morse_index, euler_characteristic
from .spacetime import inside_lightcone, future_lightcone
from .bridge import floor_smooth, sum_via_integral, product_via_integral, gamma_via_riemann_sum
from .electronic_structure import (
    fermi_occupation, tight_binding_chain_energies,
    find_chemical_potential, total_energy_smeared,
    tight_binding_dos_continuum, continuum_filling, continuum_energy, continuum_find_mu,
)
from .theory import (
    max_gradient_location, max_gradient_value, is_single_passing_at_zero, fusion_is_safe,
    fusion_error_bound,
    or_gradient_closed_form, gradient_landscape_stats, or_fusion_disagreement_rate,
    and_partial_dilation_invariance, or_breaks_partial_dilation_invariance,
    or_second_resonance_w0, or_second_resonance_location, or_second_resonance_numeric_argmax,
    or_full_gradient_magnitude_argmax,
    or_misclassification_boundary_sum, or_misclassification_boundary_numeric, or_value,
    or_n_misclassification_K, or_n_misclassification_boundary_sum,
    or_n_misclassification_boundary_numeric, or_n_value,
    or_n_threshold_Cstar, or_n_fold_error_bound, or_n_fusion_is_safe, or_n_naive_fold,
    or_n_trigger_condition_is_not_necessary,
    xor_2d_boundary_v_given_large_u, xor_2d_boundary_numeric,
    xnor_2d_boundary_v_given_large_u, xnor_2d_boundary_numeric,
    exact_not_log_identity, or_n_exact_master_equation_lhs,
    or_n_exact_master_equation_rhs, or_n_exact_threshold_last_value,
    and_n_naive_fold, and_naive_fold_matches_exactly_at_n2,
    extended_xor_family,
    not_tower_threshold_exact,
    not_tower_threshold_limit, not_tower_backward_orbit,
    or_n_cumulative_prefix_min, or_n_cumulative_trigger_is_safe,
    or_n_double_not_map, or_n_double_not_unstable_fixed_point,
    or_n_log_domain_score, or_n_log_domain_to_bounded,
    signed_log_domain_score,
    or_n_log_kicked_map, or_n_naive_fold_via_log_recursion,
    and_or_unified_threshold,
    or_n_kicked_map_unstable_point, or_n_max_rule_predicts_agreement,
    or_n_tree_fold, or_n_tree_fold_via_log_recursion,
    or_n_kicked_walk_crosses, or_n_crossing_predicts_agreement,
    or_n_agree_false_certificate, or_n_agree_true_certificate,
    or_n_agreement_sandwich,
    or_n_kicked_map_unstable_point_asymptotic,
    or_n_optimal_fold_order, or_n_fold_with_optimal_order,
    or_n_least_firing_fold_order, or_n_firing_is_order_dependent,
    or_n_optimal_fold_fires, or_n_descending_is_crossing_argmax,
    or_n_kicked_map_slope_at_unstable_point,
    or_n_accumulation_has_no_meanfield_criticality,
    nand_threshold_ab, nand_threshold_numeric, gate_dilation_type,
    nor_misclassification_boundary_sum, nor_misclassification_boundary_numeric,
    xor_zero_cross_section_threshold, xor_zero_cross_section_numeric,
    xor_diagonal_lower_threshold, xor_diagonal_upper_threshold, xor_diagonal_threshold_numeric,
    xnor_zero_cross_section_threshold, xnor_zero_cross_section_numeric,
    not_composition_tower, not_tower_threshold, not_tower_threshold_numeric,
)
from .dynamics import (
    force_fixed_point, multiplier_at, koenigs_coordinate, abel_function, fractional_iterate,
    not_map_fixed_point, not_map_multiplier, not_map_critical_xi,
    squared_map_cubic_coefficient, squared_map_convergence_exponent,
    squared_map_quartic_coefficient, fatou_coordinate_correction_coefficient,
    fatou_coordinate_local_step_check,
    asymptotic_fatou_coordinate, asymptotic_fatou_coordinate_local_check,
)
from .identities import (
    rapidity, addition, n_tuple_angle, lambert_continued_fraction,
    mittag_leffler_sum, weierstrass_product, gudermannian, verify_identities,
    integral_of_k, integral_of_reg, integral_of_NOT, integral_of_AND_wrt_a, integral_of_sech,
)
from .gauge import (
    xi_dilation_equals_x_dilation, dilation_generator_matches_xi_generator,
    translation_dilation_algebra, hyperbolic_metric_is_scale_invariant,
    killing_vectors_of_xi_halfplane, geodesic_conserved_quantities,
    annealed_training_trajectory_hyperbolic_speed,
    local_xi_connection_symbolic, local_xi_connection_numeric,
    verify_gauge_structure,
)

__all__ = [
    "sgn", "k", "reg", "NOT", "AND", "OR", "NAND", "NOR", "XOR", "XNOR", "AND_n", "OR_n",
    "eq", "neq", "gt", "lt", "ge", "le", "DEFAULT_XI", "DEFAULT_KERNEL",
    "intf", "par", "maxf", "minf", "clamp", "modf", "delta_approx",
    "kronecker_delta", "levi_civita", "dirac_delta_integral",
    "line_intersection_y", "collatz_step", "collatz_sequence",
    "choc_bar_source",
    "KERNELS", "apply_kernel", "KERNEL_BOUNDARY_CONST",
    "kernel_log_increment", "kernel_fused_or_threshold", "kernel_fused_or_is_true",
    "log_potential", "log_charge", "chemical_potential", "occupation_from_charge",
    "effective_temperature", "log_potential_is_dilation_invariant",
    "empty_state_probability", "or_n_from_empty_state", "occupation_step_sech2",
    "free_energy_log_domain", "partition_summary", "why_no_phase_transition",
    "xi_of_time", "time_of_xi", "heat_step_profile", "heat_kernel_gaussian", "gaussian_match",
    "box_heat_kernel", "box_heat_kernel_eigen",
    "infinite_well_propagator", "infinite_well_propagator_eigen",
    "soft_gt", "soft_eq", "soft_or", "soft_and", "anneal_solve", "numeric_grad", "l2_penalty",
    "is_dont_care_variable", "find_dont_care_variables",
    "kink_profile", "kink_eom_residual", "kink_energy_exact", "topological_charge",
    "kink_shape_mode_frequency", "kink_continuum_threshold",
    "kink_zero_mode_profile", "kink_shape_mode_profile", "kink_stability_spectrum_numeric",
    "kink_antikink_collision", "kink_antikink_velocity_scan",
    "box_partition_function", "box_partition_function_exact", "witten_index_toy",
    "soft_povm", "is_valid_povm", "measurement_strength",
    "soft_measurement_kraus", "quantum_truth_value",
    "bcs_gap_equation_residual", "bcs_critical_temperature", "bcs_gap",
    "bcs_gap_zero_temperature", "bcs_universal_ratio", "BCS_UNIVERSAL_RATIO",
    "thermal_transport_window", "transport_moment", "lorenz_ratio",
    "sommerfeld_heat_capacity_coefficient", "electronic_heat_capacity",
    "wiedemann_franz_check", "LORENZ_NUMBER", "kubo_dc_conductivity",
    "curie_weiss_magnetization", "curie_weiss_susceptibility",
    "curie_weiss_slope_at_zero", "has_critical_point",
    "pauli_susceptibility", "landau_susceptibility", "total_electron_susceptibility",
    "MEAN_FIELD_BETA", "MEAN_FIELD_GAMMA", "MEAN_FIELD_AMPLITUDE", "LANDAU_PAULI_RATIO",
    "ssh_transition_energies", "dielectric_imaginary", "spectral_weight", "absorbance",
    "cie_color_matching", "spectrum_to_xyz", "xyz_to_srgb", "srgb_to_hex",
    "transmitted_color", "HC_EV_NM",
    "eps2_from_hamiltonian", "material_color_from_hamiltonian", "color_saturation",
    "disordered_chain", "inverse_participation_ratio", "localization_length",
    "localization_exponent", "one_dimension_has_no_mobility_edge",
    "transfer_matrix_lambda", "scaling_beta_function", "anderson3d_critical_exponent",
    "transfer_matrix_lambda_2d", "beta_function_2d", "dimensional_beta_survey",
    "anderson3d_hamiltonian", "ipr_times_n_3d",
    "mean_level_spacing", "smeared_dos_at_zero", "resolution_exponent",
    "resolution_exponent_auto", "level_statistics_window_probe",
    "required_xi_for_accuracy",
    "PICKET_EXPONENT", "GOE_EXPONENT", "POISSON_EXPONENT",
    "ANDERSON_WC", "ANDERSON_LAMBDA_C", "ANDERSON_NU",
    "classify_bifurcation", "bcs_linear_coefficient", "bcs_beta_amplitude",
    "curie_weiss_beta_amplitude", "bifurcation_survey",
    "PITCHFORK", "PERIOD_DOUBLING", "NO_BIFURCATION",
    "gaussian_variance", "differential_entropy_gaussian",
    "fisher_information_gaussian", "de_bruijn_check",
    "fisher_metric_gaussian", "fisher_metric_matches_gauge_hyperbolic_metric",
    "fisher_gaussian_curvature",
    "morse_index", "euler_characteristic",
    "inside_lightcone", "future_lightcone",
    "floor_smooth", "sum_via_integral", "product_via_integral", "gamma_via_riemann_sum",
    "fermi_occupation", "tight_binding_chain_energies",
    "find_chemical_potential", "total_energy_smeared",
    "tight_binding_dos_continuum", "continuum_filling", "continuum_energy", "continuum_find_mu",
    "max_gradient_location", "max_gradient_value", "is_single_passing_at_zero", "fusion_is_safe",
    "fusion_error_bound",
    "or_gradient_closed_form", "gradient_landscape_stats", "or_fusion_disagreement_rate",
    "and_partial_dilation_invariance", "or_breaks_partial_dilation_invariance",
    "or_second_resonance_w0", "or_second_resonance_location", "or_second_resonance_numeric_argmax",
    "or_full_gradient_magnitude_argmax",
    "or_misclassification_boundary_sum", "or_misclassification_boundary_numeric", "or_value",
    "or_n_misclassification_K", "or_n_misclassification_boundary_sum",
    "or_n_misclassification_boundary_numeric", "or_n_value",
    "or_n_threshold_Cstar", "or_n_fold_error_bound", "or_n_fusion_is_safe", "or_n_naive_fold",
    "or_n_trigger_condition_is_not_necessary",
    "xor_2d_boundary_v_given_large_u", "xor_2d_boundary_numeric",
    "xnor_2d_boundary_v_given_large_u", "xnor_2d_boundary_numeric",
    "exact_not_log_identity", "or_n_exact_master_equation_lhs",
    "or_n_exact_master_equation_rhs", "or_n_exact_threshold_last_value",
    "and_n_naive_fold", "and_naive_fold_matches_exactly_at_n2",
    "extended_xor_family",
    "not_tower_threshold_exact",
    "not_tower_threshold_limit", "not_tower_backward_orbit",
    "or_n_cumulative_prefix_min", "or_n_cumulative_trigger_is_safe",
    "or_n_double_not_map", "or_n_double_not_unstable_fixed_point",
    "or_n_log_domain_score", "or_n_log_domain_to_bounded",
    "signed_log_domain_score",
    "or_n_log_kicked_map", "or_n_naive_fold_via_log_recursion",
    "and_or_unified_threshold",
    "or_n_kicked_map_unstable_point", "or_n_max_rule_predicts_agreement",
    "or_n_tree_fold", "or_n_tree_fold_via_log_recursion",
    "or_n_kicked_walk_crosses", "or_n_crossing_predicts_agreement",
    "or_n_agree_false_certificate", "or_n_agree_true_certificate",
    "or_n_agreement_sandwich",
    "or_n_kicked_map_unstable_point_asymptotic",
    "or_n_optimal_fold_order", "or_n_fold_with_optimal_order",
    "or_n_least_firing_fold_order", "or_n_firing_is_order_dependent",
    "or_n_optimal_fold_fires", "or_n_descending_is_crossing_argmax",
    "or_n_kicked_map_slope_at_unstable_point",
    "or_n_accumulation_has_no_meanfield_criticality",
    "nand_threshold_ab", "nand_threshold_numeric", "gate_dilation_type",
    "nor_misclassification_boundary_sum", "nor_misclassification_boundary_numeric",
    "xor_zero_cross_section_threshold", "xor_zero_cross_section_numeric",
    "xor_diagonal_lower_threshold", "xor_diagonal_upper_threshold", "xor_diagonal_threshold_numeric",
    "xnor_zero_cross_section_threshold", "xnor_zero_cross_section_numeric",
    "not_composition_tower", "not_tower_threshold", "not_tower_threshold_numeric",
    "force_fixed_point", "multiplier_at", "koenigs_coordinate", "abel_function", "fractional_iterate",
    "not_map_fixed_point", "not_map_multiplier", "not_map_critical_xi",
    "squared_map_cubic_coefficient", "squared_map_convergence_exponent",
    "squared_map_quartic_coefficient", "fatou_coordinate_correction_coefficient",
    "fatou_coordinate_local_step_check",
    "asymptotic_fatou_coordinate", "asymptotic_fatou_coordinate_local_check",
    "rapidity", "addition", "n_tuple_angle", "lambert_continued_fraction",
    "mittag_leffler_sum", "weierstrass_product", "gudermannian", "verify_identities",
    "integral_of_k", "integral_of_reg", "integral_of_NOT", "integral_of_AND_wrt_a", "integral_of_sech",
    "xi_dilation_equals_x_dilation", "dilation_generator_matches_xi_generator",
    "translation_dilation_algebra", "hyperbolic_metric_is_scale_invariant",
    "killing_vectors_of_xi_halfplane", "geodesic_conserved_quantities",
    "annealed_training_trajectory_hyperbolic_speed",
    "local_xi_connection_symbolic", "local_xi_connection_numeric",
    "verify_gauge_structure",
]

__version__ = "0.94.0"
